# -*- coding: utf-8 -*-
"""genailab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15GsjdilW-E46AIEGOzLJoqz5TjA7BD55
"""

# Install required libraries
!pip install transformers torch accelerate -q

# Import required modules
from transformers import pipeline

# Load GPT-Neo 125M model from Hugging Face
generator = pipeline(
    "text-generation",
    model="EleutherAI/gpt-neo-125M"
)

print("GPT-Neo-125M model loaded successfully!")

# Import required libraries

import torch

from transformers import pipeline

# Model Selection for E-commerce Product Description Generation

model_name = "EleutherAI/gpt-neo-125M"

# Load the text generation pipeline
generator = pipeline(
    "text-generation",
    model=model_name
)

print("Selected Model :", model_name)
print("Model loaded successfully for e-commerce product description generation.")

# Load the selected GPT-Neo model

from transformers import pipeline

# Model name
model_name = "EleutherAI/gpt-neo-125M"

# Load text generation pipeline
generator = pipeline(
    "text-generation",
    model=model_name
)

print("GPT-Neo-125M model loaded successfully!")

# Configuration for product description generation

# Product details
product_name = "Wireless Bluetooth Headphones"

features = [
    "Noise Cancellation",
    "40 Hours Battery Life",
    "Fast Charging",
    "Bluetooth 5.3",
    "Comfortable Ear Cushions"
]

# Convert features list into text
features_text = ", ".join(features)

# Create prompt for the model
prompt = f"""
Generate an attractive e-commerce product description.

Product Name: {product_name}

Features:
{features_text}

Product Description:
"""

print(prompt)

# Error Handling for GPT-Neo Product Description Generation

try:

    # Check if product name is empty
    if not product_name.strip():
        raise ValueError("Product name cannot be empty.")

    # Check if features list is empty
    if len(features) == 0:
        raise ValueError("Features list cannot be empty.")

    # Generate text using the model
    output = generator(
        prompt,
        max_length=120,
        temperature=0.8,
        num_return_sequences=1
    )

    # Print generated description
    print("Generated Product Description:\n")
    print(output[0]['generated_text'])

except ValueError as ve:
    print("Value Error :", ve)

except Exception as e:
    print("An error occurred :", e)

# Function for Product Description Generation

def generate_description(temp_value):

    try:

        # Generate product description
        output = generator(
            prompt,
            max_length=120,
            temperature=temp_value,
            num_return_sequences=1
        )

        # Print output
        print("\n===================================")
        print(f"Temperature : {temp_value}")
        print("===================================\n")

        print(output[0]['generated_text'])

    except Exception as e:
        print("Error during text generation :", e)

# Accept user input

product_name = input("Enter Product Name : ")

features_input = input("Enter Product Features (comma separated) : ")

# Convert features into list
features = features_input.split(",")

# Convert list into text
features_text = ", ".join(features)

# Create prompt
prompt = f"""
Generate an attractive e-commerce product description.

Product Name: {product_name}

Features:
{features_text}

Product Description:
"""


# Call function for different temperature values

generate_description(0.4)

generate_description(0.8)

generate_description(1.2)

# Product details entered directly in the code

product_name = "Smart Fitness Watch"

features = [
    "Heart Rate Monitoring",
    "Water Resistant",
    "7 Days Battery Life",
    "Sleep Tracking",
    "Bluetooth Calling"
]

# Convert features list into text
features_text = ", ".join(features)

# Create prompt
prompt = f"""
Generate an attractive e-commerce product description.

Product Name: {product_name}

Features:
{features_text}

Product Description:
"""

print("Product Name :", product_name)
print("Features :", features_text)

# Temperature parameters for text generation

temperature_values = [0.4, 0.8, 1.2]

# Generate outputs for each temperature
for temp in temperature_values:
    generate_description(temp)

# Testing the GPT-Neo model

try:

    print("Testing the model...\n")

    test_output = generator(
        prompt,
        max_length=100,
        temperature=0.8,
        num_return_sequences=1
    )

    print("Model Test Successful!\n")

    print("Generated Output:\n")
    print(test_output[0]['generated_text'])

except Exception as e:

    print("Model Test Failed!")
    print("Error :", e)

# Debugging Code for GPT-Neo Product Description Generator

print("========== DEBUGGING STARTED ==========\n")

# Check product details
print("Checking Product Information...\n")

print("Product Name :", product_name)
print("Features :", features)

# Check prompt creation
print("\nChecking Prompt...\n")
print(prompt)

# Check model loading
print("\nChecking Model Status...\n")

if generator:
    print("Model loaded successfully!")
else:
    print("Model not loaded!")

# Test generation process
print("\nTesting Text Generation...\n")

try:

    debug_output = generator(
        prompt,
        max_length=80,
        temperature=0.8,
        num_return_sequences=1
    )

    print("Text generation successful!\n")

    print("Generated Text:\n")
    print(debug_output[0]['generated_text'])

except Exception as e:

    print("Error Found During Generation!")
    print("Error :", e)

print("\n========== DEBUGGING COMPLETED ==========")

# Generate Three Different Outputs using Three Temperature Values

temperatures = [0.4, 0.8, 1.2]

for temp in temperatures:

    try:

        output = generator(
            prompt,
            max_length=120,
            temperature=temp,
            num_return_sequences=1
        )

        print("\n================================================")
        print(f"Generated Output for Temperature : {temp}")
        print("================================================\n")

        print(output[0]['generated_text'])

    except Exception as e:

        print(f"Error at Temperature {temp} :", e)









